New commit

diff --git a/.github/workflows/mydvc.yml b/.github/workflows/mydvc.yml
--- a/.github/workflows/mydvc.yml
+++ b/.github/workflows/mydvc.yml
@@ -12,17 +12,17 @@ jobs:
         uses: actions/checkout@v3
       - name: Install dependencies
         run: |
-          python3 -m venv venv
-          cd venv
-          . ./bin/activate
+          #python3 -m venv venv
+          #cd venv
+          #. ./bin/activate
           pip install --upgrade setuptools wheel
           pip install -r ../requirements.txt
       - name: Initialization
         run: |
-          cd venv
-          echo 'Now you will see dvc path'
-          which dvc || echo "DVC not found in PATH"
-          python -m site
-          pwd
+          #cd venv
+          #echo 'Now you will see dvc path'
+          #which dvc || echo "DVC not found in PATH"
+          #python -m site
+          #pwd
           git init
           dvc init
